spring:
  application:
    name: solgit-backend-module
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

rabbitmq:
  queues:
    MATTERMOST.NOTI:
      exchange: solgit.main.exchange
      routing-key: mattermost.noti
    MATTERMOST.CREATE:
      exchange: solgit.main.exchange
      routing-key: mattermost.create
    MATTERMOST.UPDATE:
      exchange: solgit.main.exchange
      routing-key: mattermost.update


    
server:
  port: 8085

logging:
  level:
    com.solgit.backend: INFO
    org.springframework.amqp: DEBUG
